name: watch-task-status

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  watch-task:
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DISCORD_WEBHOOK_TASK_STATUS: ${{ secrets.DISCORD_WEBHOOK_TASK_STATUS }}
          USERS: ${{ secrets.USERS }}
          TZ: "Asia/Tokyo"
        run: |
          python WatchChangeTaskStatus.py
