name: watch-deadline-task

on:
  schedule:
    - cron: '* * 10 * *'

jobs:
  watch-task:
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          PRIVATE_DB: ${{ secrets.DB }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DEADLINE_LIMIT_DAYS: ${{ secrets.DEADLINE_LIMIT_DAYS }}
          TZ: "Asia/Tokyo"
        run: |
          python WatchDeadTask.py
